### ISSUE TITLE
TypeError: set(['987654321']) is not JSON serializable

### ISSUE THREAD

**Issue by MyGGaN** [clxcommunications/sdk-xms-python#2]
Trying out the **Sending batches** example form the tutorial using iPython (Python 2.7.10).

    In [1]: import clx.xms
    In [2]: client = clx.xms.Client('xxxxxx', 'xxxxxx')
    In [3]: batch_params = clx.xms.api.MtBatchTextSmsCreate()
    In [4]: batch_params.sender = '12345'
    In [5]: batch_params.recipients = {'987654321'}
    In [6]: batch_params.body = 'Hello, World!'
    In [7]: result = client.create_batch(batch_params)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-7-31e71c9c9d95> in <module>()
    ----> 1 result = client.create_batch(batch_params)

    /myXMS/clx/xms/client.pyc in create_batch(self, batch)
        251             fields = serialize.text_batch(batch)
        252
    --> 253         response = self._post(self._url('/batches'), fields)
        254         return deserialize.batch_result(response)
        255

    /myXMS/clx/xms/client.pyc in _post(self, url, fields)
        228     def _post(self, url, fields):
        229         resp = self._session.post(
    --> 230             url, json=fields, headers=self._headers(), timeout=self._timeout)
        231         return self._check_response(resp)
        232

    /myXMS/requests/sessions.pyc in post(self, url, data, json, **kwargs)
        533         """
        534
    --> 535         return self.request('POST', url, data=data, json=json, **kwargs)
        536
        537     def put(self, url, data=None, **kwargs):

    /myXMS/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
        472             hooks = hooks,
        473         )
    --> 474         prep = self.prepare_request(req)
        475
        476         proxies = proxies or {}

    /myXMS/requests/sessions.pyc in prepare_request(self, request)
        405             auth=merge_setting(auth, self.auth),
        406             cookies=merged_cookies,
    --> 407             hooks=merge_hooks(request.hooks, self.hooks),
        408         )
        409         return p

    /myXMS/requests/models.pyc in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
        303         self.prepare_headers(headers)
        304         self.prepare_cookies(cookies)
    --> 305         self.prepare_body(data, files, json)
        306         self.prepare_auth(auth, url)
        307

    /myXMS/requests/models.pyc in prepare_body(self, data, files, json)
        443             # provides this natively, but Python 3 gives a Unicode string.
        444             content_type = 'application/json'
    --> 445             body = complexjson.dumps(json)
        446             if not isinstance(body, bytes):
        447                 body = body.encode('utf-8')

    /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.pyc in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, sort_keys, **kw)
        241         cls is None and indent is None and separators is None and
        242         encoding == 'utf-8' and default is None and not sort_keys and not kw):
    --> 243         return _default_encoder.encode(obj)
        244     if cls is None:
        245         cls = JSONEncoder

    /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.pyc in encode(self, o)
        205         # exceptions aren't as detailed.  The list call should be roughly
        206         # equivalent to the PySequence_Fast that ''.join() would do.
    --> 207         chunks = self.iterencode(o, _one_shot=True)
        208         if not isinstance(chunks, (list, tuple)):
        209             chunks = list(chunks)

    /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.pyc in iterencode(self, o, _one_shot)
        268                 self.key_separator, self.item_separator, self.sort_keys,
        269                 self.skipkeys, _one_shot)
    --> 270         return _iterencode(o, 0)
        271
        272 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

    /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.pyc in default(self, o)
        182
        183         """
    --> 184         raise TypeError(repr(o) + " is not JSON serializable")
        185
        186     def encode(self, o):

    TypeError: set(['987654321']) is not JSON serializable

**Comment by rycee** [comment]
Good catch. Originally the code used lists and I missed changing the test suite after switching over to sets causing the JSON encoding issue to be hidden since the test suite still serialized lists.

I uploaded 1.0.dev5 to testpypi with this issue fixed.
